### ISSUE TITLE
Build a Automatic Slider for the Past Events Section

### ISSUE THREAD

**Issue by mondalraj** [ADGITM2020/CodeChefADGITM#28]
<img width="1308" alt="Screenshot 2023-04-01 at 1 00 27 PM" src="https://user-images.githubusercontent.com/69672093/229272271-d192de71-fe2e-45d6-bcc6-c71b8ae3ece3.png">

Reference URL - https://codechefadgitm.vercel.app/#past-events

Expected Result - 
![image](https://user-images.githubusercontent.com/69672093/229272331-cf267216-9899-4f0d-b1f5-ac923b3592ba.png)

**Comment by mondalraj** [comment]
Automatically show the next 2 past events in 3 seconds timeout.
Also clicking on the circles will show events associated with that index

@AnishHazra and @aryansingla  Please do the following.
If you need any help you can contact @Pranshu321  or @mondalraj .

Thanks

**Comment by aryansingla** [comment]
@mondalraj I have completed work on this issue , you can verify it.
Thanks.

**Comment by mondalraj** [comment]
Need some enhancement, please fix then as discussed in whatsapp then close the issue @aryansingla
