### ISSUE TITLE
Add all the social links and Navigation links for the footer

### ISSUE THREAD

**Issue by mondalraj** [ADGITM2020/CodeChefADGITM#29]
<img width="1407" alt="Screenshot 2023-04-01 at 1 07 48 PM" src="https://user-images.githubusercontent.com/69672093/229272620-6c5f9d58-43d9-4947-a280-710779601b7d.png">

@BTANISHA11 Please do the following 
@dhankarsimran will guide you through if you want any guidance

Thanks

**Comment by mondalraj** [comment]
https://linktr.ee/codechefadgitm

Social Media Link URLs

For the phone number - Add this no - +918475008968
And keep it in anchor tag with `tel:918475008968` property

**Comment by BTANISHA11** [comment]
pushed and merged
